Adiciona o capítulo 'Jogos de Risco e Brigas Generalizadas'
rmobis/estatuto-intercomp pull request #13
Opened 2019-02-13 12:18 UTC by danilo-valente

2019-02-27 02:11 UTC, rmobis approved these changes
Faremos votação até 27/02 às 23h59

2019-02-27 02:11 UTC, rmobis commented on principal/jogos-de-risco-e-brigas.tex
> +	Em caso de empate na votação da Comissão Organizadora o jogo será considerado de risco.
altas indentação errada

2019-03-09 01:02 UTC, brudel requested changes
Fica inconveniente ter uma segunda entidade, mesmo que específica para o jogo, chamada Comissão Organizadora, o nome poderia ser mudado para Comitê Representante ou algo assim

2019-03-15 19:20 UTC, rmobis commented
Comissão Organizado diz respeito à C.O. É a mesma entidade.

2019-04-19 05:59 UTC, rmobis commented
Aprovado por **Unicamp**, **UFJF**, **UFSCar**, **FATEC**, **CAASO**, **EACH**.
**UEM** e **USJT** ausentes.

2019-04-19 06:00 UTC, merged